# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lbforum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lbforum.Post', verbose_name='Last post'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post_topics', to='lbforum.Post', verbose_name='Last post'),
        ),
    ]
